package com.renatiux.dinosexpansion;

import com.renatiux.dinosexpansion.client.dimension.DinoDimensionRenderInfo;
import com.renatiux.dinosexpansion.common.world.DEFeatures;
import com.renatiux.dinosexpansion.core.init.*;
import com.renatiux.dinosexpansion.util.CompostablesDE;
import com.renatiux.dinosexpansion.util.FlammablesDE;
import com.renatiux.dinosexpansion.util.StrippablesDE;
import net.minecraft.client.world.DimensionRenderInfo;
import net.minecraft.util.text.TranslationTextComponent;
import net.minecraft.world.gen.feature.Feature;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.renatiux.dinosexpansion.common.entities.dinosaurs.Allosaurus;
import com.renatiux.dinosexpansion.core.config.DEModConfig;
import com.renatiux.dinosexpansion.util.CutoutRendersDE;

import net.minecraft.item.crafting.IRecipeSerializer;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import software.bernie.geckolib3.GeckoLib;

// The value here should match an entry in the META-INF/mods.toml file
@Mod("dinosexpansion")
public class Dinosexpansion {
	// Directly reference a log4j logger.
	public static final Logger LOGGER = LogManager.getLogger();
	public static final String MODID = "dinosexpansion";
	
	public static final ResourceLocation modLoc(String name) {
		return new ResourceLocation(MODID, name);
	}

	public static TranslationTextComponent test(String type, String key)
	{
		return new TranslationTextComponent(type + "." + MODID + "." + key);
	}

	public static boolean ENABLE_OVERWORLD_TREES = true;

	public Dinosexpansion() {
		IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();
		ModLoadingContext.get().registerConfig(net.minecraftforge.fml.config.ModConfig.Type.COMMON, DEModConfig.init(new ForgeConfigSpec.Builder()));
		GeckoLib.initialize();
		// Register the setup method for modloading
		bus.addListener(this::setup);
		bus.addListener(this::doClientStuff);
		bus.addListener(this::registerEntityAttributes);
		
		bus.addGenericListener(IRecipeSerializer.class ,RecipeInit::registerRecipes);

		// Register ourselves for server and other game events we are interested in
		MinecraftForge.EVENT_BUS.register(this);

		BlockInit.MACHINES.register(bus);
		BlockInit.PLANTS.register(bus);
		ItemInit.ITEMS.register(bus);
		ItemInit.ARROWS.register(bus);
		ItemInit.AUTOGENERATED_ITEMS.register(bus);
		
		TileEntityTypesInit.TILE_ENTITY_TYPES.register(bus);
		ContainerTypeInit.CONTAINER_TYPES.register(bus);
		EntityTypeInit.ENTITY_TYPES.register(bus);
		EntityTypeInit.ARROW_ENTITY_TYPES.register(bus);
		
		SoundInit.SOUNDS.register(bus);

		BiomeInit.register(bus);

		SurfaceBuilderInit.SURFACE_BUILDER.register(bus);

		WorldTypeInit.setup();
	}

	private void setup(final FMLCommonSetupEvent event) {

		event.enqueueWork(DimensionInit::initBiomeSourcesAndChunkGenerator);
		
	}

	private void doClientStuff(final FMLClientSetupEvent event) {

		CutoutRendersDE.renderCutOuts();
		FlammablesDE.flammablesDE();
		StrippablesDE.strippableDE();
		CompostablesDE.compostablesDE();

		DimensionRenderInfo baseRender = new DinoDimensionRenderInfo();

		DimensionRenderInfo.field_239208_a_.put(Dinosexpansion.modLoc("dino_render"), baseRender);

	}
	
	private void registerEntityAttributes(EntityAttributeCreationEvent event) {
		event.put(EntityTypeInit.ALLOSAURUS.get(), Allosaurus.setCustomAttributes().create());
	}

	@Mod.EventBusSubscriber(modid = MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
	public static class RegistriesDE {

		@SubscribeEvent
		public static void registerFeatures(RegistryEvent.Register<Feature<?>> event) {
			DEFeatures.init();
			DEFeatures.features.forEach(feature -> event.getRegistry().register(feature));
		}

	}
}
