package com.renatiux.dinosexpansion.datagen.client;

import com.renatiux.dinosexpansion.Dinosexpansion;
import com.renatiux.dinosexpansion.core.init.ItemInit;

import net.minecraft.data.DataGenerator;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.client.model.generators.ModelFile;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.fml.RegistryObject;

public class ModItemModelsProvider extends ItemModelProvider{
	
	public final ModelFile generated;

	public ModItemModelsProvider(DataGenerator generator, ExistingFileHelper existingFileHelper) {
		super(generator, Dinosexpansion.MODID, existingFileHelper);
		generated = getExistingFile(mcLoc("item/generated"));
	}
	
	@Override
	protected void registerModels() {
		registerArrows();
		registerAutoGeneratedItems();
	}
	
	private void registerArrows() {
		ItemInit.ARROWS.getEntries().stream().map(RegistryObject::get).forEach(item -> {
			registerSimpleModel(item);
		});
	}
	
	private void registerAutoGeneratedItems() {
		ItemInit.AUTOGENERATED_ITEMS.getEntries().stream().map(RegistryObject::get).forEach(item -> {
			registerSimpleModel(item);
		});
	}
	
	private void registerSimpleModel(Item item){
		String name = item.getRegistryName().getPath();
		getBuilder(name).parent(generated).texture("layer0", "item/" + name);
	}


}
